name: gfortran - latest version

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash

    if: github.repository_owner == 'MODFLOW-USGS'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.5
      with:
        update-conda: true

    - name: Setup symbolic links on Linux
      if: runner.os == 'Linux'
      run: |
        sudo ln -fs /usr/bin/gfortran-10 /usr/local/bin/gfortran
        sudo ln -fs /usr/bin/gcc-10 /usr/local/bin/gcc
        sudo ln -fs /usr/bin/g++-10 /usr/local/bin/g++

    - name: Setup symbolic link to gfortran on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        sudo ln -fs /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
        sudo ln -fs /usr/local/bin/gcc-10 /usr/local/bin/gcc
        sudo ln -fs /usr/local/bin/g++-10 /usr/local/bin/g++

    - name: Print GNU compiler versions
      run: |
        gfortran --version
        gcc --version
        g++ --version

    - name: Install python packages
      run: |
        .github/common/install-python.sh

    - name: Print conda version
      run: |
        conda --version

    - name: Print python package versions
      run: |
        .github/common/python-version.sh

    - name: Build applications
      run: |
        nosetests -v --with-id --with-timer -w ./autotest build_mf2005_apps.py

    - name: Test applications
      run: |
        nosetests -v --with-id --with-timer -w ./autotest
